import {COLORS} from "@/src/styles/colors";
import {StyleSheet} from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F7FA",
  },
  centered: {
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: COLORS.GRAY,
  },
  statusHeader: {
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 8,
    backgroundColor: COLORS.WHITE,
    marginBottom: 12,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    shadowColor: "#000",
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  statusBadge: {
    width: 64,
    height: 64,
    borderRadius: 32,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  statusText: {
    color: COLORS.DARK,
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 8,
  },
  orderInfoBox: {
    alignItems: "center",
    paddingTop: 8,
  },
  orderId: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.PRIMARY,
    marginBottom: 4,
  },
  orderDate: {
    fontSize: 13,
    color: COLORS.GRAY,
  },
  cancelReasonHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 12,
    paddingTop: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: "#FEF2F2",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#FEE2E2",
    maxWidth: "90%",
  },
  cancelReasonHeaderText: {
    flex: 1,
    fontSize: 13,
    color: "#DC2626",
    fontWeight: "500",
    fontStyle: "italic",
  },
  card: {
    backgroundColor: COLORS.WHITE,
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 12,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    gap: 8,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.DARK,
  },
  timeline: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingHorizontal: 8,
  },
  timelineItem: {
    flex: 1,
    alignItems: "center",
    position: "relative",
  },
  timelineContent: {
    alignItems: "center",
    zIndex: 1,
  },
  timelineCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 3,
    borderColor: "#E0E0E0",
    backgroundColor: COLORS.WHITE,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
  },
  timelineCircleCompleted: {
    backgroundColor: COLORS.SUCCESS,
    borderColor: COLORS.SUCCESS,
  },
  timelineCircleCurrent: {
    backgroundColor: COLORS.PRIMARY,
    borderColor: COLORS.PRIMARY,
    transform: [{scale: 1.1}],
  },
  timelineLabel: {
    fontSize: 11,
    color: COLORS.GRAY,
    textAlign: "center",
    lineHeight: 14,
    paddingHorizontal: 2,
    maxWidth: 70,
  },
  timelineLabelCompleted: {
    color: COLORS.DARK,
    fontWeight: "600",
  },
  timelineLine: {
    position: "absolute",
    height: 3,
    width: "100%",
    backgroundColor: "#E0E0E0",
    top: 20,
    left: "50%",
    zIndex: 0,
  },
  timelineLineCompleted: {
    backgroundColor: COLORS.SUCCESS,
  },
  itemRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
    gap: 12,
  },
  itemBadge: {
    backgroundColor: COLORS.PRIMARY,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    minWidth: 40,
    alignItems: "center",
  },
  itemQtyBadge: {
    color: COLORS.WHITE,
    fontSize: 13,
    fontWeight: "700",
  },
  itemInfo: {
    flex: 1,
  },
  itemName: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.DARK,
    marginBottom: 2,
  },
  itemUnitPrice: {
    fontSize: 12,
    color: COLORS.GRAY,
  },
  itemPrice: {
    fontSize: 15,
    fontWeight: "700",
    color: COLORS.PRIMARY,
  },
  infoBox: {
    gap: 12,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    paddingVertical: 8,
  },
  noteRow: {
    backgroundColor: "#FFF9E6",
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: "#FFD700",
  },
  infoText: {
    fontSize: 14,
    color: COLORS.DARK,
    flex: 1,
    lineHeight: 20,
  },
  paymentBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8F9FA",
    padding: 16,
    borderRadius: 12,
    gap: 12,
    borderWidth: 1,
    borderColor: "#E8E8E8",
  },
  paymentIconBox: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: COLORS.WHITE,
    justifyContent: "center",
    alignItems: "center",
  },
  paymentText: {
    fontSize: 15,
    fontWeight: "600",
    color: COLORS.DARK,
    flex: 1,
  },
  summaryBox: {
    gap: 4,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 8,
  },
  summaryLabel: {
    fontSize: 14,
    color: COLORS.GRAY,
  },
  summaryValue: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.DARK,
  },
  discountRow: {
    backgroundColor: "#E8F5E9",
    marginHorizontal: -16,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  discountLabelBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  discountLabel: {
    color: COLORS.SUCCESS,
    fontWeight: "600",
    fontSize: 14,
  },
  discountValue: {
    color: COLORS.SUCCESS,
    fontWeight: "700",
    fontSize: 15,
  },
  summaryDivider: {
    height: 1,
    backgroundColor: "#E0E0E0",
    marginVertical: 12,
  },
  totalRow: {
    paddingVertical: 4,
  },
  totalLabel: {
    fontSize: 17,
    fontWeight: "700",
    color: COLORS.DARK,
  },
  totalValue: {
    fontSize: 20,
    fontWeight: "800",
    color: COLORS.PRIMARY,
  },
  bottomPadding: {
    height: 20,
  },
  footer: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: COLORS.WHITE,
    borderTopWidth: 1,
    borderTopColor: "#E8E8E8",
    shadowColor: "#000",
    shadowOffset: {width: 0, height: -2},
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 8,
  },
  buttonRow: {
    flexDirection: "row",
    gap: 12,
  },
  halfButton: {
    flex: 1,
  },
  fullButton: {
    flex: 1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: COLORS.WHITE,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 32,
    maxHeight: "85%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: COLORS.DARK,
  },
  closeButton: {
    padding: 4,
  },
  modalSubtitle: {
    fontSize: 14,
    color: COLORS.GRAY,
    marginBottom: 24,
  },
  starContainer: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
    marginBottom: 16,
    paddingVertical: 12,
  },
  starButton: {
    padding: 4,
  },
  ratingText: {
    textAlign: "center",
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.PRIMARY,
    marginBottom: 24,
  },
  commentInput: {
    marginBottom: 20,
  },
  submitButton: {
    width: "100%",
  },
});

export default styles;
