import {COLORS} from "@/src/styles/colors";
import {StyleSheet} from "react-native";

const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: "#F9FAFB"},
  centered: {justifyContent: "center", alignItems: "center"},
  loadingText: {marginTop: 12, fontSize: 14, color: COLORS.GRAY},
  header: {
    backgroundColor: COLORS.WHITE,
    borderBottomWidth: 1,
    margin: -12,
    borderBottomColor: "#E5E7EB",
    marginBottom: 8,
  },
  titleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    padding: 8,
    paddingBottom: 0,
  },
  headerTitle: {fontSize: 18, fontWeight: "bold", color: COLORS.DARK},
  headerSubtitle: {fontSize: 14, color: COLORS.GRAY},
  sortButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: COLORS.LIGHT_GRAY,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  sortButtonText: {fontSize: 13, color: COLORS.PRIMARY, fontWeight: "600"},
  sortMenu: {
    backgroundColor: COLORS.WHITE,
    borderRadius: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    shadowColor: "#000",
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 1,
  },
  sortMenuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  sortMenuItemActive: {backgroundColor: "#FFF5F5"},
  sortMenuText: {flex: 1, fontSize: 14, color: COLORS.DARK},
  sortMenuTextActive: {color: COLORS.PRIMARY, fontWeight: "600"},
  tabsContainer: {marginTop: 4, paddingLeft: 8, paddingRight: 8},
  tabsList: {paddingVertical: 8, gap: 8},
  tabItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#F3F4F6",
    marginRight: 8,
  },
  tabItemActive: {backgroundColor: "#FFF5F5", borderWidth: 1, borderColor: COLORS.PRIMARY + "30"},
  tabIconContainer: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: COLORS.WHITE,
    justifyContent: "center",
    alignItems: "center",
  },
  tabIconContainerActive: {backgroundColor: COLORS.PRIMARY + "15"},
  tabText: {fontSize: 13, color: COLORS.GRAY, fontWeight: "500"},
  tabTextActive: {color: COLORS.PRIMARY, fontWeight: "600"},
  tabBadge: {
    backgroundColor: COLORS.GRAY + "20",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
    minWidth: 20,
    alignItems: "center",
  },
  tabBadgeActive: {backgroundColor: COLORS.PRIMARY},
  tabBadgeText: {fontSize: 11, fontWeight: "bold", color: COLORS.GRAY},
  tabBadgeTextActive: {color: COLORS.WHITE},
  listContent: {paddingHorizontal: 16, paddingVertical: 12, flexGrow: 1},
  emptyState: {flex: 1, marginTop: 60},
  orderCard: {
    backgroundColor: COLORS.WHITE,
    borderRadius: 16,
    marginBottom: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    shadowColor: "#000",
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  orderHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 12,
  },
  orderTitle: {flex: 1, marginRight: 12},
  orderIdRow: {flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 6},
  orderId: {fontSize: 16, fontWeight: "bold", color: COLORS.DARK},
  statusDot: {width: 8, height: 8, borderRadius: 4},
  orderDate: {fontSize: 12, color: COLORS.GRAY},
  statusBadge: {paddingVertical: 6, paddingHorizontal: 12, borderRadius: 8, borderWidth: 1},
  statusText: {fontSize: 12, fontWeight: "600"},
  orderBody: {flexDirection: "row", alignItems: "center", paddingHorizontal: 16, paddingVertical: 12, gap: 12},
  infoRow: {flexDirection: "row", alignItems: "center", gap: 6},
  infoIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: "#F3F4F6",
    justifyContent: "center",
    alignItems: "center",
  },
  infoText: {fontSize: 14, color: COLORS.DARK, fontWeight: "500"},
  divider: {width: 1, height: 24, backgroundColor: "#E5E7EB"},
  totalAmount: {fontSize: 16, color: COLORS.SUCCESS, fontWeight: "700"},
  orderFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#F9FAFB",
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
  },
  tapText: {fontSize: 13, color: COLORS.PRIMARY, fontWeight: "600"},
  loadingFooter: {flexDirection: "row", justifyContent: "center", alignItems: "center", paddingVertical: 20, gap: 8},
  loadingFooterText: {fontSize: 13, color: COLORS.GRAY},
});

export default styles;
